int AddFunc(char* pstrFuncName,int iFuncEntryName);
int AddHostAPI(LINKEDLIST* pList,char* pstrHostAPIName);
int AddInstr(char* pstrMnenonic,int iOpcode,int iOpCount);
int AddLabel(char* pstrIdentName,int iTargetIndex,int iWorkingFuncIndex);
int AddNode(LINKEDLIST* pList,void* pvData);
int AddString(LINKEDLIST* pList,char* pstrString);
int AddSymbol(char* pstrIdentName,int iSize,int iStackUnitIndex,int iWorkingFuncIndex);
void CharExpectedErrorAndExit(char c);
FUNCCONTROL CreateFuncContorlBlock();
void CreateInstrDictionary();
void dy();
void Exit();
void ExitOnError(char* pstrErrorMsg);
void FreeLinkedList(LINKEDLIST* pList);
char GetAndLookAheadAChar();
char* GetCurrLexeme();
FUNCNODE* GetFuncByName(char* pstrFuncName);
int GetInstrByMnemonic(INSTRDIRNODE* pInstr,char* pstrMnemonic);
LABELNODE* GetLabelByIdent(char* pstrIdentName,int iWorkingFuncIndex);
Token GetNextToken();
SYMBOLNODE* GetSymbolByIndex(char* pstrIdentName,int iWorkingFuncIndex);
int GetSymbolSizeByIdent(char* pstrIdentName,int iWorkingFuncIndex);
int GetSymbolStackUnitIndexByIdent(char* pstrIdentName,int iWorkingFuncIndex);
void InitLinkedList(LINKEDLIST* pList);
void Parsing();
void ResetFuncControlBlock(FUNCCONTROL* Block);
void ResetLexer();
void ResultingCodeErrorAndExit(char* pstErrorMsg);
void SetAllowOpTypeForInstr(int iInstrIndex,int iOpIndex,allow_op_type_bit_cmb iOpType);
void SetFuncInfo(char* pstrFuncName,int iParamCount,int iLocalDataSize);
int SkipNextLine();
void StripComments(char* pstrSourceCodeLine);
void TrimWhitespace(char* pstrString);
